import 'package:cloud_firestore/cloud_firestore.dart';

/// Model representing a lost or found item posted by a campus student.
class LostItem {
  const LostItem({
    required this.id,
    required this.title,
    required this.location,
    required this.imageUrl,
    required this.userId,
    required this.userName,
    required this.userEmail,
    required this.createdAt,
    this.description = '',
    this.storagePath = '',
    this.contactInfo = '',
    this.isClaimed = false,
  });

  /// Unique item ID generated by Cloud Firestore
  final String id;

  /// What the item is (e.g. "Earbud", "Blue Water Bottle", "ID Card")
  final String title;

  /// Where the item was found (e.g. "Lecture Room 5", "Library 2nd Floor")
  final String location;

  /// HTTPS photo URL from Cloudinary or legacy Firebase Storage.
  final String imageUrl;

  /// `cloudinary:<public_id>` for new photos, or a legacy Firebase Storage path.
  final String storagePath;

  /// Additional notes or details about the item
  final String description;

  /// Instructions on how the owner can get it or contact the finder
  final String contactInfo;

  /// UID of the student who posted this item
  final String userId;

  /// Display name of the student who posted
  final String userName;

  /// Email of the student who posted
  final String userEmail;

  /// True if the owner has collected or claimed the item
  final bool isClaimed;

  /// Timestamp in milliseconds since epoch
  final int createdAt;

  /// Convert to Map for saving in Cloud Firestore
  Map<String, dynamic> toMap() => {
    'id': id,
    'title': title,
    'location': location,
    'imageUrl': imageUrl,
    'storagePath': storagePath,
    'description': description,
    'contactInfo': contactInfo,
    'userId': userId,
    'userName': userName,
    'userEmail': userEmail,
    'isClaimed': isClaimed,
    'createdAt': createdAt,
  };

  /// Create a LostItem instance from a Firestore Map
  factory LostItem.fromMap(String id, Map<dynamic, dynamic> map) {
    final createdAt = map['createdAt'];

    return LostItem(
      id: id,
      title: (map['title'] as String?) ?? '',
      location: (map['location'] as String?) ?? '',
      imageUrl: (map['imageUrl'] as String?) ?? '',
      storagePath: (map['storagePath'] as String?) ?? '',
      description: (map['description'] as String?) ?? '',
      contactInfo: (map['contactInfo'] as String?) ?? '',
      userId: (map['userId'] as String?) ?? '',
      userName: (map['userName'] as String?) ?? 'Anonymous Student',
      userEmail: (map['userEmail'] as String?) ?? '',
      isClaimed: (map['isClaimed'] as bool?) ?? false,
      createdAt: createdAt is Timestamp
          ? createdAt.millisecondsSinceEpoch
          : (createdAt as int?) ?? DateTime.now().millisecondsSinceEpoch,
    );
  }

  /// Create a copy of the item with updated fields
  LostItem copyWith({
    String? id,
    String? title,
    String? location,
    String? imageUrl,
    String? storagePath,
    String? description,
    String? contactInfo,
    String? userId,
    String? userName,
    String? userEmail,
    bool? isClaimed,
    int? createdAt,
  }) {
    return LostItem(
      id: id ?? this.id,
      title: title ?? this.title,
      location: location ?? this.location,
      imageUrl: imageUrl ?? this.imageUrl,
      storagePath: storagePath ?? this.storagePath,
      description: description ?? this.description,
      contactInfo: contactInfo ?? this.contactInfo,
      userId: userId ?? this.userId,
      userName: userName ?? this.userName,
      userEmail: userEmail ?? this.userEmail,
      isClaimed: isClaimed ?? this.isClaimed,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}
